steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "${_BRANCH_NAME}" = "main" ]; then
          gcloud app deploy app.prod.yaml --quiet; # Change this if your production config has a different name
        elif [ "${_BRANCH_NAME}" = "dev" ]; then
          gcloud app deploy app.dev.yaml --quiet;
        else
          echo "Branch '${_BRANCH_NAME}' not configured for deployment";
          exit 1
        fi
substitutions:
  _BRANCH_NAME: "${BRANCH_NAME}"

options:
  logging: NONE
